[project]
name = "chirper"
version = "0.1.0"
description = "A Twitter/X like web application, named Chirper, built using Django."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.6",
    "django-allauth>=65.4.0",
]
