# Generated by Django 5.1.6 on 2025-03-05 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chirp',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
