# Generated by Django 5.1.6 on 2025-03-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_chirp_like_counter'),
    ]

    operations = [
    ]
