# Generated by Django 5.1.6 on 2025-03-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0002_chirp_like_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chirp',
            old_name='like_counter',
            new_name='likes',
        ),
    ]
