# Generated by Django 5.1.6 on 2025-03-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0003_merge_0002_chirp_like_counter_0002_chirp_likes'),
        ('chirper', '0003_rename_like_counter_chirp_likes'),
    ]

    operations = [
    ]
