# Generated by Django 5.1.6 on 2025-03-16 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chirper", "0004_alter_chirp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirp",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="chirper.chirp",
            ),
        ),
    ]
