# Generated by Django 5.1.6 on 2025-03-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirper', '0004_merge_20250308_0231'),
        ('chirper', '0006_like'),
    ]

    operations = [
    ]
